version: "2"

run:
  timeout: 10m
  go: "1.21"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - contextcheck
    - dupl
    - gosec
    - misspell
    - revive
  disable:
    - cyclop # Disabled due to complex test functions and config parsing

  settings:
    revive:
      rules:
        - name: indent-error-flow
        - name: unused-parameter
        - name: var-naming

  exclusions:
    rules:
      # Allow higher complexity in test files
      - path: ".*_test\\.go"
        linters:
          - cyclop
