version: "2"

run:
  go: "1.21"
  timeout: 10m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - gosec
    - misspell
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  cyclop:
    max-complexity: 15

  dupl:
    threshold: 100

  gosec:
    excludes:
      - G204 # Subprocess launched with variable - we need this for xcaddy
      - G304 # File path provided as taint input - test files

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - dupl
    - path: integration_test\.go
      linters:
        - gosec
    - text: "exported"
      linters:
        - revive
      source: "func.*Test.*"
